### ISSUE TITLE
Can't clone. Might be on my end somehow but I don't know.

### ISSUE THREAD

**Issue by BurnDivision** [scionaltera/agonyforge#152]
I've done this before on Linux, but this is Git for Windows. Please forgive me if I'm missing something that I should have done myself.

` git clone git@github.com:scionaltera/agonyforge.git
Cloning into 'agonyforge'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
`

**Comment by scionaltera** [comment]
That command line looks like it ought to work. Everything is public on my end as far as I know. Cloning over SSH on GitHub does require that you authenticate with an SSH key that is registered with your GitHub account, so that's what I'd check first: which key is it trying to use, and is that same key listed on your SSH keys page on GitHub?

https://github.com/settings/keys

The following docs might be some help too:

https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey

**Comment by BurnDivision** [comment]
OK. I had trouble getting the public key work when I was using private key instructions. That's where I went wrong, 🤷 

Thanks for the help still and I hope to get a lot of using this project.
